import { EvidenceCheckIsland } from "@/components/evidence/evidence-check-island";
import { checkPlace, KnownGateApiError } from "@/lib/knowngate/api";
import type { PlaceResult } from "@/lib/knowngate/contracts";
import { questionText } from "@/lib/knowngate/contracts";
export const dynamic = "force-dynamic";
async function load(name:string):Promise<{place?:PlaceResult;missing?:boolean}>{try{return{place:await checkPlace({restrictions:[{key:"peanut"}],venue:{name}})}}catch(error){return{missing:error instanceof KnownGateApiError&&error.status===404}}}
export default async function VenuePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const name=slug.split("-").map(x=>x[0]?.toUpperCase()+x.slice(1)).join(" ");const result=await load(name);if(!result.place)return <Unavailable missing={result.missing}/>;const place=result.place;return <main className="ruling-room"><header className="masthead"><div><p className="eyebrow">KNOWNGATE / VENUE EVIDENCE</p><h1>{place.venue.name}</h1></div><p className="doctrine">Published chart.<br/>Read date shown.</p></header><section className="panel premise-panel"><p className="step">CHART / {place.chart.replaceAll("_"," ")}</p><h2>{place.venue.chain}</h2><p>{place.verdict_counts.conflict} conflict · {place.verdict_counts.ask_one_question} ask one question</p>{place.notable.map(item=><article className="notable" key={item.subject.value}><strong>{item.subject.name}</strong><p>{questionText(item.question)??item.verdict.replaceAll("_"," ")}</p></article>)}<Mno items={place.must_not_omit}/><p className="source">SOURCE / {place.source?`${place.source.name} / READ ${place.source.read_date}`:"Source unavailable"}</p></section><EvidenceCheckIsland subject={{kind:"menu_item",value:place.notable[0]?.subject.value??"Menu item",venue:place.venue.name}}/></main>}
function Unavailable({missing}:{missing?:boolean}){return <main className="ruling-room"><section className="panel premise-panel"><p className="eyebrow">CANNOT VERIFY</p><h1>Venue evidence could not be reached</h1><p>{missing?"No published evidence was found for this venue.":"No verdict was produced. The evidence service could not be reached; try again later."}</p></section></main>}
/** Labelled in the text itself so a model reading this page relays it whole. */
function Mno({items}:{items?:string[]}){if(!items||!items.length)return null;return <div className="kg-must-not-omit"><ul>{items.map(i=><li key={i}><span className="mno-label">MUST NOT OMIT:</span> {i}</li>)}</ul></div>}
